name: Code Standards Check

on:
  pull_request:
    paths:
      - 'app/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      # Add more paths as needed

jobs:
  code_standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHP_CodeSniffer on changed files
        run: ./vendor/bin/phpcs --standard=PSR2 --extensions=php ${{ steps.changed-files.outputs.all_changed_files }}
