name: Code Standards Check

on:
  pull_request:
    paths:
      - 'app/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      # Add more paths as needed

jobs:
  code_standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Get changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base=$(curl -sSL https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r '.base.sha')
            echo "::set-output name=files::$(git diff --name-only $base ${{ github.sha }} | grep '\.php$')"
          else
            echo "::set-output name=files::$(git diff --name-only HEAD^..HEAD | grep '\.php$')"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP_CodeSniffer
        run: |
          if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
            ./vendor/bin/phpcs --standard=PSR2 --extensions=php ${{ steps.changed-files.outputs.files }}
          else
            echo "No PHP files changed. Skipping PHP_CodeSniffer."
          fi
