name: Code Standards Check

on:
  pull_request:
    paths:
      - 'app/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      # Add more paths as needed

jobs:
  code_standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Get modified files
        id: get_modified_files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(app|config|database|public|resources|routes)/.*\.php$' | paste -sd, -)"

      - name: Run PHP_CodeSniffer on modified files
        run: |
          IFS=',' read -ra files <<< "${{ steps.get_modified_files.outputs.files }}"
          if [ -n "$files" ]; then
            ./vendor/bin/phpcs --standard=PSR2 --extensions=php "${files[@]}"
          else
            echo "No modified PHP files found."
          fi
