name: Code Standards Check

on:
  pull_request:
    paths:
      - 'app/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      # Add more paths as needed

jobs:
  code_standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Get modified PHP files
        id: get_modified_files
        run: echo "::set-output name=files::$(git log -m -1 --name-only --pretty=format: ${{ github.event.before }}...${{ github.sha }} | grep '\.php$' | xargs)"

      - name: Run PHPStan on modified files
        run: ./vendor/bin/phpstan analyze --level=7 ${{ steps.get_modified_files.outputs.files }}

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=PSR2 --extensions=php app/ tests/

      - name: Check for modified files
        run: git diff --name-only --exit-code || (echo "Code Standards Check failed. Please run PHPStan and PHP_CodeSniffer locally and fix the issues." && exit 1)
