name: Code Standards Check

on:
  pull_request:
    paths:
      - 'app/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      - 'tests/**'

jobs:
  check-code-standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # You can adjust the PHP version as needed

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no

      - name: Check for changes
        run: git diff --exit-code
